package Views;

import static Enums.BeestType.HERBIVOOR;
import static Enums.BeestType.OMNIVOOR;
import Models.Beest;
import Models.Leefgebied;
import Models.WereldModel;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Bart Janisse
 */
public class WereldView extends javax.swing.JPanel implements Observer{
  

//    JPanel leefgebied_links;
//    JPanel leefgebied_rechts;
    WereldModel model;
     
    /**
     * Creates new form WereldView
     */
    public WereldView() {
        initComponents();
        this.setBackground(Color.blue);
        
//        leefgebied_links = new JPanel(true);
//        leefgebied_links.setVisible(true);
//        leefgebied_links.setBackground(Color.WHITE);
//        
//        leefgebied_rechts = new JPanel(true);
//        leefgebied_rechts.setVisible(true);
//        leefgebied_rechts.setBackground(Color.WHITE);
        
        
    }
    
    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        tekenLeefgebied(g, 110, 110);
        tekenLeefgebied(g, 750, 110);
        
        if(model != null)
        {
            int i = 0;
            for(Leefgebied leefgebied: model.getLeefgebieden())
            {
                for(Beest beest: leefgebied.getBeesten())
                {
                    int X = beest.getPositie().getX();
                    int Y = beest.getPositie().getY();
                    
                    Color kleur;
                    
                    switch(beest.getType())
                    {
                        case CARNIVOOR : kleur = Color.RED;
                                         break;
                        case OMNIVOOR  : kleur = Color.YELLOW;
                                         break;
                        case HERBIVOOR : kleur = new Color(182,122,87);
                                         break;
                        case NONIVOOR  : kleur = new Color(163,73,164);
                                         break;
                        default: kleur = Color.BLACK;
                    }
                    int offsetX = 110 + i * 640;
                    tekenBeest(g, kleur, X * 5 + offsetX, Y * 4 + 110 );
                }
                i++;
                
            }
        }

    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void update(Observable o, Object arg) 
    {
        
        model = (WereldModel)o;
        this.repaint();            
    }
    
    private void tekenLeefgebied(Graphics g, int posX, int posY)
    {
        g.setColor(Color.WHITE);
        g.fillRect(posX, posY, 510, 410);   
    }
    
    private void tekenBeest(Graphics g, Color color, int posX, int posY)
    {
        g.setColor(color);
        g.fillRect(posX, posY, 10, 10);
    }
    
}
