/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_algemeen;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.w3c.dom.Document;
import org.w3c.dom.*;

import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author patje
 */
public class SimulatieGegevensDialog extends javax.swing.JDialog {
    
        private final instellingenBeest instellingenCarnivoor     = new instellingenBeest();
        private final instellingenBeest instellingenOmnivoor      = new instellingenBeest();
        private final instellingenBeest instellingenHerbivoor     = new instellingenBeest();
        private final instellingenBeest instellingenNonivoor      = new instellingenBeest();
        private final instellingenPlant instellingenPlanten       = new instellingenPlant();

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form NewOkCancelDialog
     */
    public SimulatieGegevensDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // met onderstaande regel wordt de lokatie van de dialog in het midden van het scherm gezet.
        this.setLocationRelativeTo(null);
        readXMLfile();
        this.addTabs();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(725, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Instellingen voor het aanmaken van een nieuwe simulatie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if ((this.getCarnivoorAantalPoten() > 0) && (this.getHerbivoorAantalPoten()>0) && (this.getOmnivoorAantalPoten()>0) && (this.getNonivoorAantalPoten()>0))
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatieGegevensDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatieGegevensDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatieGegevensDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatieGegevensDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SimulatieGegevensDialog dialog = new SimulatieGegevensDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
    
    private void addTabs()
    {
        
        
        
        ImageIcon iconPlant     = new ImageIcon(getClass().getResource("groen.png"));
        ImageIcon iconCanivoor  = new ImageIcon(getClass().getResource("rood.png"));
        ImageIcon iconOmnivoor  = new ImageIcon(getClass().getResource("geel.png"));
        ImageIcon iconHerbivoor = new ImageIcon(getClass().getResource("bruin.png"));
        ImageIcon iconNonivoor  = new ImageIcon(getClass().getResource("paars.png"));
        
        this.jTabbedPane1.addTab("Carnivoor  ",iconCanivoor, instellingenCarnivoor);
        this.jTabbedPane1.addTab("Omnivoor  ", iconOmnivoor, instellingenOmnivoor);
        this.jTabbedPane1.addTab("Herbivoor  ", iconHerbivoor, instellingenHerbivoor);
        this.jTabbedPane1.addTab("Nonivoor  ", iconNonivoor, instellingenNonivoor);
        this.jTabbedPane1.addTab("Plant  ",iconPlant, instellingenPlanten);
        
       instellingenPlanten.setVoedingsWaarde(1200);
       
    }
    /**
     * retourneerd het ingevoerde aantal poten van een Carnivoor
     * @return 
     */
    public int getCarnivoorAantalPoten()
    {
        return this.instellingenCarnivoor.getAantalPoten();
    }
    /**
     * retourneerd het ingevoerde maximale gewicht van een Carnivoor
     * @return 
     */
    public int getCarnivoorMaxGewicht()
    {
        return this.instellingenCarnivoor.getMaximaalGewicht();
    }
    /**
     * retourneerd het ingevoerde maximale energie niveau van een Carnivoor
     * @return 
     */
    public int getCarnivoorMaxEnergie()  
    {
        return this.instellingenCarnivoor.getMaximaalEnergie();
    }
    
    /**
     * retourneerd het ingevoerde aantal poten van een Herbivoor
     * @return 
     */
    public int getHerbivoorAantalPoten()
    {
        return this.instellingenHerbivoor.getAantalPoten();
    }
    /**
     * retourneerd het ingevoerde maximale gewicht van een Herbivoor
     * @return 
     */
    public int getHerbivoorMaxGewicht()
    {
        return this.instellingenHerbivoor.getMaximaalGewicht();
    }
    /**
     * retourneerd het ingevoerde maximale energie niveau van een Herbivoor
     * @return 
     */
    public int getHerbivoorMaxEnergie()
    {
        return this.instellingenHerbivoor.getMaximaalEnergie();
    }
     
    /**
     * retourneerd het ingevoerde aantal poten van een Omnivoor
     * @return 
     */
    public int getOmnivoorAantalPoten()
    {
        return this.instellingenOmnivoor.getAantalPoten();
    }
    /**
     * retourneerd het ingevoerde maximale gewicht van een Omnivoor
     * @return 
     */
    public int getOmnivoorMaxGewicht()
    {
        return this.instellingenOmnivoor.getMaximaalGewicht();
    }
    /**
     * retourneerd het ingevoerde maximale energie niveau van een Omnivoor
     * @return 
     */
    public int getOmnivoorMaxEnergie() 
    {
       return this.instellingenOmnivoor.getMaximaalEnergie();
    }
    
    /**
     * retourneerd het ingevoerde aantal poten van een Nonivoor
     * @return 
     */
    public int getNonivoorAantalPoten()
    {
        return this.instellingenNonivoor.getAantalPoten();
    }
    /**
     * retourneerd het ingevoerde maximale gewicht van een Nonivoor
     * @return 
     */
    public int getNonivoorMaxGewicht()
    {
        return this.instellingenNonivoor.getMaximaalGewicht();
    }
    /**
     * retourneerd het ingevoerde maximale energie niveau van een Nonivoor
     * @return 
     */
    public int getNonivoorMaxEnergie() 
    {
        return this.instellingenNonivoor.getMaximaalEnergie();
    }
    
    /**
     * retourneerd het ingevoerde voedingswaarde van een plant
     * @return 
     */
    public int getPlantVoedingsWaarde()
    {
        return this.instellingenPlanten.getVoedingsWaarde();
    }
    
    private void readXMLfile()
    {
        try
        {
         DocumentBuilderFactory docBuilderFactory = DocumentBuilderFactory.newInstance();
         DocumentBuilder docBuilder = docBuilderFactory.newDocumentBuilder();
         Document doc = docBuilder.parse (new File("LifeSettings.xml"));
         
         // normalize text representation
         doc.getDocumentElement().normalize();
         
         NodeList listOfXMLobjects = doc.getElementsByTagName("XMLObject");
         
         String[] typeBeest = new String[listOfXMLobjects.getLength()];
         int[] aantalPoten = new int[listOfXMLobjects.getLength()];
         int[] maxGewicht = new int[listOfXMLobjects.getLength()];
         int[] maxEnergie = new int[listOfXMLobjects.getLength()];
         for (int s=0; s<listOfXMLobjects.getLength(); s++)
         {
             Node firstXMLobjectNode = listOfXMLobjects.item(s);
             if (firstXMLobjectNode.getNodeType() == Node.ELEMENT_NODE)
             {
               Element EerstBeestElement = (Element)firstXMLobjectNode;
                         
                //-------
                NodeList typeList = EerstBeestElement.getElementsByTagName("typeBeest");
                Element typeBeestElement = (Element)typeList.item(0);
                NodeList typeBeestNodeList = typeBeestElement.getChildNodes();  
                
                NodeList aantPList = EerstBeestElement.getElementsByTagName("aantalPoten");
                Element aantalPotenElement = (Element)aantPList.item(0);
                NodeList aantalPotenNodeList = aantalPotenElement.getChildNodes();

                NodeList maxGewichtList = EerstBeestElement.getElementsByTagName("maxGewicht");
                Element maxGewichtElement = (Element)maxGewichtList.item(0);
                NodeList maxGewichtNodeList = maxGewichtElement.getChildNodes();
                
                NodeList maxEnergieList = EerstBeestElement.getElementsByTagName("maxEnergie");
                Element maxEnergieElement = (Element)maxEnergieList.item(0);
                NodeList maxEnergieNodeList = maxEnergieElement.getChildNodes();
               
                
                typeBeest[s]    = (String)typeBeestNodeList.item(0).getNodeValue().trim();
                aantalPoten[s]  =  Integer.valueOf(aantalPotenNodeList.item(0).getNodeValue());
                maxGewicht[s]   =   Integer.valueOf(maxGewichtNodeList.item(0).getNodeValue());
                maxEnergie[s]   = Integer.valueOf(maxEnergieNodeList.item(0).getNodeValue());       
             }
         }
        // laad init waarde
       instellingenCarnivoor.setAantalPoten( aantalPoten[0]);
       instellingenCarnivoor.setMaxGewicht( maxGewicht[0]);
       instellingenCarnivoor.setMaxEnergie( maxEnergie[0]);
       
       instellingenOmnivoor.setAantalPoten( aantalPoten[1]);
       instellingenOmnivoor.setMaxGewicht( maxGewicht[1]);
       instellingenOmnivoor.setMaxEnergie( maxEnergie[1]);
       
       instellingenHerbivoor.setAantalPoten( aantalPoten[2]);
       instellingenHerbivoor.setMaxGewicht( maxGewicht[2]);
       instellingenHerbivoor.setMaxEnergie( maxEnergie[2]);
       
       instellingenNonivoor.setAantalPoten( aantalPoten[3]);
       instellingenNonivoor.setMaxGewicht( maxGewicht[3]);
       instellingenNonivoor.setMaxEnergie( maxEnergie[3]);
         
        }   
        catch (  SAXException | IOException | ParserConfigurationException ex)
        {
                JOptionPane.showMessageDialog(null,"Er is iets mis gegaan met de XML parse : " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }
}
